package youtube

import "strings"

// LooksLikeMusic reports whether a video is music-leaning using Data API fields only
// (no InnerTube). Used for musicUrl and musicOnly filters.
func LooksLikeMusic(v Video) bool {
	return looksLikeMusicFields(v.CategoryID, v.ChannelTitle, v.Title, "")
}

// FilterMusic returns only music-leaning videos (preserves order).
func FilterMusic(videos []Video) []Video {
	out := make([]Video, 0, len(videos))
	for i := range videos {
		if LooksLikeMusic(videos[i]) {
			out = append(out, videos[i])
		}
	}
	return out
}

func looksLikeMusicFields(categoryID, channelTitle, title, description string) bool {
	if categoryID == CategoryMusic {
		return true
	}
	ch := strings.TrimSpace(channelTitle)
	if strings.HasSuffix(ch, "- Topic") || strings.HasSuffix(ch, " - Topic") {
		return true
	}
	blob := strings.ToLower(title + "\n" + description)
	for _, needle := range musicTitleHints {
		if strings.Contains(blob, needle) {
			return true
		}
	}
	return false
}

// Lowercase substrings that commonly mark music uploads on YouTube.
var musicTitleHints = []string{
	"official audio",
	"official music video",
	"official video",
	"lyric video",
	"lyrics video",
	"provided to youtube by",
	"auto-generated by youtube",
	"(audio)",
	"[audio]",
	"visualizer",
}
